(deftheme aether-prime
  "The ultimate AI-synthesized dark theme. Created 2026-04-15.")

(custom-theme-set-faces
 'aether-prime
 '(default ((t (:family "Iosevka" :foundry "nil" :width normal :height 180 :weight regular :slant normal :underline nil :overline nil :extend nil :strike-through nil :box nil :inverse-video nil :foreground "#d4d8e8" :background "#080c16" :stipple nil :inherit nil))))
 '(cursor ((t (:background "#f72585"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "#4cc9f0"))))
 '(homoglyph ((t (:foreground "#f72585"))))
 '(minibuffer-prompt ((t (:foreground "#4cc9f0" :weight semi-bold))))
 '(highlight ((t (:background "#182038"))))
 '(region ((t (:extend t :background "#1f2947"))))
 '(shadow ((t (:foreground "#42506b"))))
 '(secondary-selection ((t (:extend t :background "#2a1b3d"))))
 '(trailing-whitespace ((t (:background "#660033"))))
 '(font-lock-bracket-face ((t (:inherit (font-lock-punctuation-face) :foreground "#5c6b8c"))))
 '(font-lock-builtin-face ((t (:foreground "#4cc9f0" :slant italic))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#3a465e" :slant italic))))
 '(font-lock-comment-face ((t (:foreground "#42506b" :slant italic))))
 '(font-lock-constant-face ((t (:foreground "#fca311"))))
 '(font-lock-delimiter-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-doc-face ((t (:foreground "#6b826d" :slant italic))))
 '(font-lock-doc-markup-face ((t (:foreground "#b07dff" :slant italic))))
 '(font-lock-escape-face ((t (:foreground "#f72585" :weight bold))))
 '(font-lock-function-call-face ((t (:foreground "#4cc9f0"))))
 '(font-lock-function-name-face ((t (:foreground "#3a86ff"))))
 '(font-lock-keyword-face ((t (:foreground "#f72585"))))
 '(font-lock-negation-char-face ((t (:foreground "#ff0054"))))
 '(font-lock-number-face ((t (:foreground "#ffbe0b"))))
 '(font-lock-misc-punctuation-face ((t (:inherit (font-lock-punctuation-face) :foreground "#5c6b8c"))))
 '(font-lock-operator-face ((t (:foreground "#b07dff"))))
 '(font-lock-preprocessor-face ((t (:foreground "#d291bc"))))
 '(font-lock-property-name-face ((t (:foreground "#a3b1c6" :slant italic))))
 '(font-lock-property-use-face ((t (:foreground "#8d9eb5"))))
 '(font-lock-punctuation-face ((t (:foreground "#42506b"))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#4cc9f0" :weight bold))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#fca311" :weight bold))))
 '(font-lock-string-face ((t (:foreground "#b5e48c"))))
 '(font-lock-type-face ((t (:foreground "#fca311"))))
 '(font-lock-variable-name-face ((t (:foreground "#b07dff"))))
 '(font-lock-variable-use-face ((t (:foreground "#9b61ee"))))
 '(font-lock-warning-face ((t (:foreground "#ff0054" :weight bold :underline t))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:underline (:style line) :foreground "#4cc9f0"))))
 '(link-visited ((t (:underline (:style line) :foreground "#b07dff"))))
 '(fringe ((t (:background "#080c16"))))
 '(header-line ((t (:box nil :foreground "#a3b1c6" :background "#0d1322" :inherit (mode-line)))))
 '(tooltip ((t (:foreground "#d4d8e8" :background "#141b2d" :inherit (variable-pitch)))))
 '(mode-line ((t (:box (:line-width (1 . -1) :color "#1f2947" :style released-button) :foreground "#d4d8e8" :background "#0d1322"))))
 '(mode-line-buffer-id ((t (:foreground "#4cc9f0" :weight bold))))
 '(mode-line-emphasis ((t (:weight bold :foreground "#f72585"))))
 '(mode-line-highlight ((t (:box (:line-width (2 . 2) :color "#4cc9f0" :style released-button)))))
 '(mode-line-inactive ((t (:weight light :box (:line-width (1 . -1) :color "#0a0e1a" :style nil) :foreground "#5c6b8c" :background "#0a0e1a" :inherit (mode-line)))))
 '(isearch ((t (:foreground "#080c16" :background "#b5e48c"))))
 '(isearch-fail ((t (:foreground "#d4d8e8" :background "#ff0054"))))
 '(lazy-highlight ((t (:distant-foreground "#d4d8e8" :background "#1f4068"))))
 '(match ((t (:background "#3a0ca3" :foreground "#d4d8e8"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'aether-prime)
