(deftheme obsidian-ink
  "Obsidian Ink: A world-class IDE theme balancing Bauhaus minimalism and modern UI ergonomics. Created 2026-04-15.")

(custom-theme-set-faces
 'obsidian-ink
 '(default ((t (:family "Iosevka" :foundry "nil" :width normal :height 180 :weight regular :slant normal :underline nil :overline nil :extend nil :strike-through nil :box nil :inverse-video nil :foreground "#D1D4D9" :background "#121417" :stipple nil :inherit nil))))
 '(cursor ((t (:background "#EBCB8B"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "#88C0D0"))))
 '(homoglyph ((t (:foreground "#D08770"))))
 '(minibuffer-prompt ((t (:foreground "#81A1C1" :weight semi-bold))))
 '(highlight ((t (:background "#1A1D23"))))
 '(region ((t (:extend t :background "#263345"))))
 '(shadow ((t (:foreground "#5C6370"))))
 '(secondary-selection ((t (:extend t :background "#2E3440"))))
 '(trailing-whitespace ((t (:background "#4C566A"))))
 '(font-lock-bracket-face ((t (:inherit (font-lock-punctuation-face) :foreground "#666F7A"))))
 '(font-lock-builtin-face ((t (:foreground "#81A1C1" :slant italic))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#4C566A" :slant italic))))
 '(font-lock-comment-face ((t (:foreground "#5C6370" :slant italic))))
 '(font-lock-constant-face ((t (:foreground "#D08770"))))
 '(font-lock-delimiter-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-doc-face ((t (:foreground "#8FBCBB" :slant italic))))
 '(font-lock-doc-markup-face ((t (:foreground "#B48EAD" :slant italic))))
 '(font-lock-escape-face ((t (:foreground "#EBCB8B" :weight bold))))
 '(font-lock-function-call-face ((t (:foreground "#88C0D0"))))
 '(font-lock-function-name-face ((t (:foreground "#8FBCBB"))))
 '(font-lock-keyword-face ((t (:foreground "#81A1C1" :weight semi-bold))))
 '(font-lock-negation-char-face ((t (:foreground "#BF616A"))))
 '(font-lock-number-face ((t (:foreground "#B48EAD"))))
 '(font-lock-misc-punctuation-face ((t (:inherit (font-lock-punctuation-face) :foreground "#666F7A"))))
 '(font-lock-operator-face ((t (:foreground "#81A1C1"))))
 '(font-lock-preprocessor-face ((t (:foreground "#5E81AC"))))
 '(font-lock-property-name-face ((t (:foreground "#D1D4D9" :slant italic))))
 '(font-lock-property-use-face ((t (:foreground "#D1D4D9"))))
 '(font-lock-punctuation-face ((t (:foreground "#666F7A"))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#EBCB8B" :weight bold))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#B48EAD" :weight bold))))
 '(font-lock-string-face ((t (:foreground "#A3BE8C"))))
 '(font-lock-type-face ((t (:foreground "#8FBCBB"))))
 '(font-lock-variable-name-face ((t (:foreground "#D1D4D9"))))
 '(font-lock-variable-use-face ((t (:foreground "#D1D4D9"))))
 '(font-lock-warning-face ((t (:foreground "#D08770" :weight bold))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:underline (:style line) :foreground "#88C0D0"))))
 '(link-visited ((t (:underline (:style line) :foreground "#B48EAD"))))
 '(fringe ((t (:background "#121417"))))
 '(header-line ((t (:box nil :foreground "#5C6370" :background "#1A1D23" :inherit (mode-line)))))
 '(tooltip ((t (:foreground "#D1D4D9" :background "#1E222A" :inherit (variable-pitch)))))
 '(mode-line ((t (:box (:line-width (1 . -1) :color "#2E3440" :style released-button) :foreground "#A3A9B5" :background "#1A1D23"))))
 '(mode-line-buffer-id ((t (:foreground "#81A1C1" :weight bold))))
 '(mode-line-emphasis ((t (:weight bold :foreground "#D1D4D9"))))
 '(mode-line-highlight ((t (:box (:line-width (2 . 2) :color "#88C0D0" :style released-button)))))
 '(mode-line-inactive ((t (:weight light :box (:line-width (1 . -1) :color "#121417" :style nil) :foreground "#4C566A" :background "#121417" :inherit (mode-line)))))
 '(isearch ((t (:foreground "#121417" :background "#EBCB8B"))))
 '(isearch-fail ((t (:foreground "#BF616A" :background "#2E3440"))))
 '(lazy-highlight ((t (:distant-foreground "#D1D4D9" :background "#3B4252"))))
 '(match ((t (:background "#434C5E" :foreground "#D1D4D9"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'obsidian-ink)
