(deftheme vinda
  "Created 2026-04-14.")

(custom-theme-set-faces
 'vinda
 '(default ((t (:family "Iosevka" :foundry "nil" :width normal :height 180 :weight regular :slant normal :underline nil :overline nil :extend nil :strike-through nil :box nil :inverse-video nil :foreground "#c8c8d4" :background "#0d0f18" :stipple nil :inherit nil))))
 '(cursor ((t (:background "#d4a04e"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "#5eaed0"))))
 '(homoglyph ((t (:foreground "#c87050"))))
 '(minibuffer-prompt ((t (:foreground "#d4a04e" :weight semi-bold))))
 '(highlight ((t (:background "#1e2040"))))
 '(region ((t (:extend t :background "#1e2040"))))
 '(shadow ((t (:foreground "#505068"))))
 '(secondary-selection ((t (:extend t :background "#252848"))))
 '(trailing-whitespace ((t (:background "#3a1020"))))
 '(font-lock-bracket-face ((t (:inherit (font-lock-punctuation-face) :foreground "#606080"))))
 '(font-lock-builtin-face ((t (:foreground "#5eaed0" :slant italic))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#454860" :slant italic))))
 '(font-lock-comment-face ((t (:foreground "#505868" :slant italic))))
 '(font-lock-constant-face ((t (:foreground "#c87088"))))
 '(font-lock-delimiter-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-doc-face ((t (:foreground "#508868" :slant italic))))
 '(font-lock-doc-markup-face ((t (:foreground "#8a70b0" :slant italic))))
 '(font-lock-escape-face ((t (:foreground "#d4a04e" :weight bold))))
 '(font-lock-function-call-face ((t (:foreground "#68aed0"))))
 '(font-lock-function-name-face ((t (:foreground "#5eaed0"))))
 '(font-lock-keyword-face ((t (:foreground "#d4a04e"))))
 '(font-lock-negation-char-face ((t (:foreground "#d47050"))))
 '(font-lock-number-face ((t (:foreground "#d49058"))))
 '(font-lock-misc-punctuation-face ((t (:inherit (font-lock-punctuation-face) :foreground "#686888"))))
 '(font-lock-operator-face ((t (:foreground "#8070a0"))))
 '(font-lock-preprocessor-face ((t (:foreground "#c090d0"))))
 '(font-lock-property-name-face ((t (:foreground "#9ea8b8" :slant italic))))
 '(font-lock-property-use-face ((t (:foreground "#8a94a8"))))
 '(font-lock-punctuation-face ((t (:foreground "#505070"))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#d4a04e" :weight bold))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#c090d0" :weight bold))))
 '(font-lock-string-face ((t (:foreground "#68b878"))))
 '(font-lock-type-face ((t (:foreground "#a888cc"))))
 '(font-lock-variable-name-face ((t (:foreground "#9ea8b8"))))
 '(font-lock-variable-use-face ((t (:foreground "#8a94a8"))))
 '(font-lock-warning-face ((t (:foreground "#c87088" :weight bold))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:underline (:style line) :foreground "#5eaed0"))))
 '(link-visited ((t (:underline (:style line) :foreground "#a888cc"))))
 '(fringe ((t (:background "#0d0f18"))))
 '(header-line ((t (:box nil :foreground "#8a8a9e" :background "#14162a" :inherit (mode-line)))))
 '(tooltip ((t (:foreground "#c8c8d4" :background "#1a1c32" :inherit (variable-pitch)))))
 '(mode-line ((t (:box (:line-width (1 . -1) :color "#2a2a48" :style released-button) :foreground "#a0a0b8" :background "#14162a"))))
 '(mode-line-buffer-id ((t (:foreground "#d4a04e" :weight bold))))
 '(mode-line-emphasis ((t (:weight bold :foreground "#c8c8d4"))))
 '(mode-line-highlight ((t (:box (:line-width (2 . 2) :color "#5eaed0" :style released-button)))))
 '(mode-line-inactive ((t (:weight light :box (:line-width (1 . -1) :color "#1a1a30" :style nil) :foreground "#505068" :background "#0e1020" :inherit (mode-line)))))
 '(isearch ((t (:foreground "#e0c0f0" :background "#503070"))))
 '(isearch-fail ((t (:foreground "#e05050" :background "#2a1015"))))
 '(lazy-highlight ((t (:distant-foreground "#c0c0d8" :background "#261840"))))
 '(match ((t (:background "#282048"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'vinda)
